const one = "/images/cards/cards-01.png";
const two = "/images/cards/cards-02.png";
const three = "/images/cards/cards-03.png";
const four = "/images/cards/cards-04.png";

const cone = "/images/cards/cards-01.png";
const ctwo = "/images/cards/cards-02.png";
const cthree = "/images/cards/cards-03.png";
const cfour = "/images/cards/cards-04.png";
const cfive = "/images/cards/cards-05.png";
const csix = "/images/cards/cards-06.png";

const images = [
  {
    id: 1,
    src: one,
    name: "Max-Hospital-and-Diagnostics-Limited.webp",
    size: "1.2 MB",
    dimensions: "1920x1080",
    type: "image/webp",
    uploadedOn: "2024/09/18",
    uploadedBy: "Sayma",
    uploadedTo: "Max Hospital Chittagong",
  },
  {
    id: 2,
    src: two,
    name: "Parkview-Hospital-Ltd.webp",
    size: "800 KB",
    dimensions: "1280x720",
    type: "image/webp",
    uploadedOn: "2024/09/18",
    uploadedBy: "Sayma",
    uploadedTo: "Parkview Hospital Ltd",
  },
  {
    id: 3,
    src: three,
    name: "Max-Hospital.webp",
    size: "1.5 MB",
    dimensions: "2048x1536",
    type: "image/webp",
    uploadedOn: "2024/09/18",
    uploadedBy: "Sayma",
    uploadedTo: "Max Hospital Chittagong",
  },
  {
    id: 4,
    src: four,
    name: "How-to-Apply-for-MBBS-in-Bangladesh.webp",
    size: "2.1 MB",
    dimensions: "3840x2160",
    type: "image/webp",
    uploadedOn: "2024/09/17",
    uploadedBy: "Healtha Editorial Team",
    uploadedTo: "How to Apply for MBBS in Bangladesh?",
  },
  {
    id: 5,
    src: one,
    name: "EVERCARE-HOSPITAL-CHATTOGRAM.webp",
    size: "1.8 MB",
    dimensions: "1600x900",
    type: "image/webp",
    uploadedOn: "2024/09/16",
    uploadedBy: "Sayma",
    uploadedTo: "EVERCARE HOSPITAL CHATTOGRAM",
  },
  {
    id: 6,
    src: cone,
    name: "How-to-Apply-for-MBBS-in-Bangladesh.webp",
    size: "2.1 MB",
    dimensions: "3840x2160",
    type: "image/webp",
    uploadedOn: "2024/09/17",
    uploadedBy: "Healtha Editorial Team",
    uploadedTo: "How to Apply for MBBS in Bangladesh?",
  },
  {
    id: 7,
    src: ctwo,
    name: "EVERCARE-HOSPITAL-CHATTOGRAM.webp",
    size: "1.8 MB",
    dimensions: "1600x900",
    type: "image/webp",
    uploadedOn: "2024/09/16",
    uploadedBy: "Sayma",
    uploadedTo: "EVERCARE HOSPITAL CHATTOGRAM",
  },
  {
    id: 8,
    src: cthree,
    name: "How-to-Apply-for-MBBS-in-Bangladesh.webp",
    size: "2.1 MB",
    dimensions: "3840x2160",
    type: "image/webp",
    uploadedOn: "2024/09/17",
    uploadedBy: "Healtha Editorial Team",
    uploadedTo: "How to Apply for MBBS in Bangladesh?",
  },
  {
    id: 9,
    src: cfour,
    name: "EVERCARE-HOSPITAL-CHATTOGRAM.webp",
    size: "1.8 MB",
    dimensions: "1600x900",
    type: "image/webp",
    uploadedOn: "2024/09/16",
    uploadedBy: "Sayma",
    uploadedTo: "EVERCARE HOSPITAL CHATTOGRAM",
  },
  {
    id: 10,
    src: cfive,
    name: "How-to-Apply-for-MBBS-in-Bangladesh.webp",
    size: "2.1 MB",
    dimensions: "3840x2160",
    type: "image/webp",
    uploadedOn: "2024/09/17",
    uploadedBy: "Healtha Editorial Team",
    uploadedTo: "How to Apply for MBBS in Bangladesh?",
  },
  {
    id: 11,
    src: csix,
    name: "EVERCARE-HOSPITAL-CHATTOGRAM.webp",
    size: "1.8 MB",
    dimensions: "1600x900",
    type: "image/webp",
    uploadedOn: "2024/09/16",
    uploadedBy: "Sayma",
    uploadedTo: "EVERCARE HOSPITAL CHATTOGRAM",
  },
  {
    id: 122,
    src: one,
    name: "Max-Hospital-and-Diagnostics-Limited.webp",
    size: "1.2 MB",
    dimensions: "1920x1080",
    type: "image/webp",
    uploadedOn: "2024/09/18",
    uploadedBy: "Sayma",
    uploadedTo: "Max Hospital Chittagong",
  },
  {
    id: 211,
    src: two,
    name: "Parkview-Hospital-Ltd.webp",
    size: "800 KB",
    dimensions: "1280x720",
    type: "image/webp",
    uploadedOn: "2024/09/18",
    uploadedBy: "Sayma",
    uploadedTo: "Parkview Hospital Ltd",
  },
  {
    id: 133,
    src: three,
    name: "Max-Hospital.webp",
    size: "1.5 MB",
    dimensions: "2048x1536",
    type: "image/webp",
    uploadedOn: "2024/09/18",
    uploadedBy: "Sayma",
    uploadedTo: "Max Hospital Chittagong",
  },
  {
    id: 431,
    src: four,
    name: "How-to-Apply-for-MBBS-in-Bangladesh.webp",
    size: "2.1 MB",
    dimensions: "3840x2160",
    type: "image/webp",
    uploadedOn: "2024/09/17",
    uploadedBy: "Healtha Editorial Team",
    uploadedTo: "How to Apply for MBBS in Bangladesh?",
  },
  {
    id: 513,
    src: one,
    name: "EVERCARE-HOSPITAL-CHATTOGRAM.webp",
    size: "1.8 MB",
    dimensions: "1600x900",
    type: "image/webp",
    uploadedOn: "2024/09/16",
    uploadedBy: "Sayma",
    uploadedTo: "EVERCARE HOSPITAL CHATTOGRAM",
  },
  {
    id: 26,
    src: cone,
    name: "How-to-Apply-for-MBBS-in-Bangladesh.webp",
    size: "2.1 MB",
    dimensions: "3840x2160",
    type: "image/webp",
    uploadedOn: "2024/09/17",
    uploadedBy: "Healtha Editorial Team",
    uploadedTo: "How to Apply for MBBS in Bangladesh?",
  },
  {
    id: 71,
    src: ctwo,
    name: "EVERCARE-HOSPITAL-CHATTOGRAM.webp",
    size: "1.8 MB",
    dimensions: "1600x900",
    type: "image/webp",
    uploadedOn: "2024/09/16",
    uploadedBy: "Sayma",
    uploadedTo: "EVERCARE HOSPITAL CHATTOGRAM",
  },
  {
    id: 81,
    src: cthree,
    name: "How-to-Apply-for-MBBS-in-Bangladesh.webp",
    size: "2.1 MB",
    dimensions: "3840x2160",
    type: "image/webp",
    uploadedOn: "2024/09/17",
    uploadedBy: "Healtha Editorial Team",
    uploadedTo: "How to Apply for MBBS in Bangladesh?",
  },
  {
    id: 91,
    src: cfour,
    name: "EVERCARE-HOSPITAL-CHATTOGRAM.webp",
    size: "1.8 MB",
    dimensions: "1600x900",
    type: "image/webp",
    uploadedOn: "2024/09/16",
    uploadedBy: "Sayma",
    uploadedTo: "EVERCARE HOSPITAL CHATTOGRAM",
  },
  {
    id: 110,
    src: cfive,
    name: "How-to-Apply-for-MBBS-in-Bangladesh.webp",
    size: "2.1 MB",
    dimensions: "3840x2160",
    type: "image/webp",
    uploadedOn: "2024/09/17",
    uploadedBy: "Healtha Editorial Team",
    uploadedTo: "How to Apply for MBBS in Bangladesh?",
  },
];

export default images;
